/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BruksomraderRouteImport } from './routes/bruksomrader'
import { Route as DchubRouteImport } from './routes/dchub'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EnterpriseEvalueringRouteImport } from './routes/enterprise-evaluering'
import { Route as ForBankOgFinansRouteImport } from './routes/for-bank-og-finans'
import { Route as ForHrOgLedelseRouteImport } from './routes/for-hr-og-ledelse'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OmSelskapetRouteImport } from './routes/om-selskapet'
import { Route as PartnereRouteImport } from './routes/partnere'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as SikkerhetOgPersonvernRouteImport } from './routes/sikkerhet-og-personvern'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SlikFungererDetRouteImport } from './routes/slik-fungerer-det'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as EnBankingAndFinanceRouteImport } from './routes/en.banking-and-finance'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnEnterpriseEvaluationRouteImport } from './routes/en.enterprise-evaluation'
import { Route as EnHowItWorksRouteImport } from './routes/en.how-it-works'
import { Route as EnHrAndLeadershipRouteImport } from './routes/en.hr-and-leadership'
import { Route as EnPartnersRouteImport } from './routes/en.partners'
import { Route as EnPilotRouteImport } from './routes/en.pilot'
import { Route as EnSecurityAndPrivacyRouteImport } from './routes/en.security-and-privacy'
import { Route as EnUseCasesRouteImport } from './routes/en.use-cases'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BruksomraderRoute = BruksomraderRouteImport.update({
  id: '/bruksomrader',
  path: '/bruksomrader',
  getParentRoute: () => rootRouteImport,
} as any)
const DchubRoute = DchubRouteImport.update({
  id: '/dchub',
  path: '/dchub',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseEvalueringRoute = EnterpriseEvalueringRouteImport.update({
  id: '/enterprise-evaluering',
  path: '/enterprise-evaluering',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBankOgFinansRoute = ForBankOgFinansRouteImport.update({
  id: '/for-bank-og-finans',
  path: '/for-bank-og-finans',
  getParentRoute: () => rootRouteImport,
} as any)
const ForHrOgLedelseRoute = ForHrOgLedelseRouteImport.update({
  id: '/for-hr-og-ledelse',
  path: '/for-hr-og-ledelse',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OmSelskapetRoute = OmSelskapetRouteImport.update({
  id: '/om-selskapet',
  path: '/om-selskapet',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnereRoute = PartnereRouteImport.update({
  id: '/partnere',
  path: '/partnere',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const SikkerhetOgPersonvernRoute = SikkerhetOgPersonvernRouteImport.update({
  id: '/sikkerhet-og-personvern',
  path: '/sikkerhet-og-personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SlikFungererDetRoute = SlikFungererDetRouteImport.update({
  id: '/slik-fungerer-det',
  path: '/slik-fungerer-det',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBankingAndFinanceRoute = EnBankingAndFinanceRouteImport.update({
  id: '/en/banking-and-finance',
  path: '/en/banking-and-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEnterpriseEvaluationRoute = EnEnterpriseEvaluationRouteImport.update({
  id: '/en/enterprise-evaluation',
  path: '/en/enterprise-evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHowItWorksRoute = EnHowItWorksRouteImport.update({
  id: '/en/how-it-works',
  path: '/en/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHrAndLeadershipRoute = EnHrAndLeadershipRouteImport.update({
  id: '/en/hr-and-leadership',
  path: '/en/hr-and-leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPartnersRoute = EnPartnersRouteImport.update({
  id: '/en/partners',
  path: '/en/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPilotRoute = EnPilotRouteImport.update({
  id: '/en/pilot',
  path: '/en/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSecurityAndPrivacyRoute = EnSecurityAndPrivacyRouteImport.update({
  id: '/en/security-and-privacy',
  path: '/en/security-and-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnUseCasesRoute = EnUseCasesRouteImport.update({
  id: '/en/use-cases',
  path: '/en/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bruksomrader': typeof BruksomraderRoute
  '/dchub': typeof DchubRoute
  '/demo': typeof DemoRoute
  '/enterprise-evaluering': typeof EnterpriseEvalueringRoute
  '/for-bank-og-finans': typeof ForBankOgFinansRoute
  '/for-hr-og-ledelse': typeof ForHrOgLedelseRoute
  '/kontakt': typeof KontaktRoute
  '/mcp': typeof McpRoute
  '/om-selskapet': typeof OmSelskapetRoute
  '/partnere': typeof PartnereRoute
  '/pilot': typeof PilotRoute
  '/sikkerhet-og-personvern': typeof SikkerhetOgPersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slik-fungerer-det': typeof SlikFungererDetRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/en/about': typeof EnAboutRoute
  '/en/banking-and-finance': typeof EnBankingAndFinanceRoute
  '/en/contact': typeof EnContactRoute
  '/en/enterprise-evaluation': typeof EnEnterpriseEvaluationRoute
  '/en/how-it-works': typeof EnHowItWorksRoute
  '/en/hr-and-leadership': typeof EnHrAndLeadershipRoute
  '/en/partners': typeof EnPartnersRoute
  '/en/pilot': typeof EnPilotRoute
  '/en/security-and-privacy': typeof EnSecurityAndPrivacyRoute
  '/en/use-cases': typeof EnUseCasesRoute
  '/en/': typeof EnIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bruksomrader': typeof BruksomraderRoute
  '/dchub': typeof DchubRoute
  '/demo': typeof DemoRoute
  '/enterprise-evaluering': typeof EnterpriseEvalueringRoute
  '/for-bank-og-finans': typeof ForBankOgFinansRoute
  '/for-hr-og-ledelse': typeof ForHrOgLedelseRoute
  '/kontakt': typeof KontaktRoute
  '/mcp': typeof McpRoute
  '/om-selskapet': typeof OmSelskapetRoute
  '/partnere': typeof PartnereRoute
  '/pilot': typeof PilotRoute
  '/sikkerhet-og-personvern': typeof SikkerhetOgPersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slik-fungerer-det': typeof SlikFungererDetRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/en/about': typeof EnAboutRoute
  '/en/banking-and-finance': typeof EnBankingAndFinanceRoute
  '/en/contact': typeof EnContactRoute
  '/en/enterprise-evaluation': typeof EnEnterpriseEvaluationRoute
  '/en/how-it-works': typeof EnHowItWorksRoute
  '/en/hr-and-leadership': typeof EnHrAndLeadershipRoute
  '/en/partners': typeof EnPartnersRoute
  '/en/pilot': typeof EnPilotRoute
  '/en/security-and-privacy': typeof EnSecurityAndPrivacyRoute
  '/en/use-cases': typeof EnUseCasesRoute
  '/en': typeof EnIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bruksomrader': typeof BruksomraderRoute
  '/dchub': typeof DchubRoute
  '/demo': typeof DemoRoute
  '/enterprise-evaluering': typeof EnterpriseEvalueringRoute
  '/for-bank-og-finans': typeof ForBankOgFinansRoute
  '/for-hr-og-ledelse': typeof ForHrOgLedelseRoute
  '/kontakt': typeof KontaktRoute
  '/mcp': typeof McpRoute
  '/om-selskapet': typeof OmSelskapetRoute
  '/partnere': typeof PartnereRoute
  '/pilot': typeof PilotRoute
  '/sikkerhet-og-personvern': typeof SikkerhetOgPersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slik-fungerer-det': typeof SlikFungererDetRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/en/about': typeof EnAboutRoute
  '/en/banking-and-finance': typeof EnBankingAndFinanceRoute
  '/en/contact': typeof EnContactRoute
  '/en/enterprise-evaluation': typeof EnEnterpriseEvaluationRoute
  '/en/how-it-works': typeof EnHowItWorksRoute
  '/en/hr-and-leadership': typeof EnHrAndLeadershipRoute
  '/en/partners': typeof EnPartnersRoute
  '/en/pilot': typeof EnPilotRoute
  '/en/security-and-privacy': typeof EnSecurityAndPrivacyRoute
  '/en/use-cases': typeof EnUseCasesRoute
  '/en/': typeof EnIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bruksomrader'
    | '/dchub'
    | '/demo'
    | '/enterprise-evaluering'
    | '/for-bank-og-finans'
    | '/for-hr-og-ledelse'
    | '/kontakt'
    | '/mcp'
    | '/om-selskapet'
    | '/partnere'
    | '/pilot'
    | '/sikkerhet-og-personvern'
    | '/sitemap.xml'
    | '/slik-fungerer-det'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/en/about'
    | '/en/banking-and-finance'
    | '/en/contact'
    | '/en/enterprise-evaluation'
    | '/en/how-it-works'
    | '/en/hr-and-leadership'
    | '/en/partners'
    | '/en/pilot'
    | '/en/security-and-privacy'
    | '/en/use-cases'
    | '/en/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bruksomrader'
    | '/dchub'
    | '/demo'
    | '/enterprise-evaluering'
    | '/for-bank-og-finans'
    | '/for-hr-og-ledelse'
    | '/kontakt'
    | '/mcp'
    | '/om-selskapet'
    | '/partnere'
    | '/pilot'
    | '/sikkerhet-og-personvern'
    | '/sitemap.xml'
    | '/slik-fungerer-det'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/en/about'
    | '/en/banking-and-finance'
    | '/en/contact'
    | '/en/enterprise-evaluation'
    | '/en/how-it-works'
    | '/en/hr-and-leadership'
    | '/en/partners'
    | '/en/pilot'
    | '/en/security-and-privacy'
    | '/en/use-cases'
    | '/en'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bruksomrader'
    | '/dchub'
    | '/demo'
    | '/enterprise-evaluering'
    | '/for-bank-og-finans'
    | '/for-hr-og-ledelse'
    | '/kontakt'
    | '/mcp'
    | '/om-selskapet'
    | '/partnere'
    | '/pilot'
    | '/sikkerhet-og-personvern'
    | '/sitemap.xml'
    | '/slik-fungerer-det'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/en/about'
    | '/en/banking-and-finance'
    | '/en/contact'
    | '/en/enterprise-evaluation'
    | '/en/how-it-works'
    | '/en/hr-and-leadership'
    | '/en/partners'
    | '/en/pilot'
    | '/en/security-and-privacy'
    | '/en/use-cases'
    | '/en/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BruksomraderRoute: typeof BruksomraderRoute
  DchubRoute: typeof DchubRoute
  DemoRoute: typeof DemoRoute
  EnterpriseEvalueringRoute: typeof EnterpriseEvalueringRoute
  ForBankOgFinansRoute: typeof ForBankOgFinansRoute
  ForHrOgLedelseRoute: typeof ForHrOgLedelseRoute
  KontaktRoute: typeof KontaktRoute
  McpRoute: typeof McpRoute
  OmSelskapetRoute: typeof OmSelskapetRoute
  PartnereRoute: typeof PartnereRoute
  PilotRoute: typeof PilotRoute
  SikkerhetOgPersonvernRoute: typeof SikkerhetOgPersonvernRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlikFungererDetRoute: typeof SlikFungererDetRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EnAboutRoute: typeof EnAboutRoute
  EnBankingAndFinanceRoute: typeof EnBankingAndFinanceRoute
  EnContactRoute: typeof EnContactRoute
  EnEnterpriseEvaluationRoute: typeof EnEnterpriseEvaluationRoute
  EnHowItWorksRoute: typeof EnHowItWorksRoute
  EnHrAndLeadershipRoute: typeof EnHrAndLeadershipRoute
  EnPartnersRoute: typeof EnPartnersRoute
  EnPilotRoute: typeof EnPilotRoute
  EnSecurityAndPrivacyRoute: typeof EnSecurityAndPrivacyRoute
  EnUseCasesRoute: typeof EnUseCasesRoute
  EnIndexRoute: typeof EnIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruksomrader': {
      id: '/bruksomrader'
      path: '/bruksomrader'
      fullPath: '/bruksomrader'
      preLoaderRoute: typeof BruksomraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dchub': {
      id: '/dchub'
      path: '/dchub'
      fullPath: '/dchub'
      preLoaderRoute: typeof DchubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-evaluering': {
      id: '/enterprise-evaluering'
      path: '/enterprise-evaluering'
      fullPath: '/enterprise-evaluering'
      preLoaderRoute: typeof EnterpriseEvalueringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-bank-og-finans': {
      id: '/for-bank-og-finans'
      path: '/for-bank-og-finans'
      fullPath: '/for-bank-og-finans'
      preLoaderRoute: typeof ForBankOgFinansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-hr-og-ledelse': {
      id: '/for-hr-og-ledelse'
      path: '/for-hr-og-ledelse'
      fullPath: '/for-hr-og-ledelse'
      preLoaderRoute: typeof ForHrOgLedelseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-selskapet': {
      id: '/om-selskapet'
      path: '/om-selskapet'
      fullPath: '/om-selskapet'
      preLoaderRoute: typeof OmSelskapetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnere': {
      id: '/partnere'
      path: '/partnere'
      fullPath: '/partnere'
      preLoaderRoute: typeof PartnereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sikkerhet-og-personvern': {
      id: '/sikkerhet-og-personvern'
      path: '/sikkerhet-og-personvern'
      fullPath: '/sikkerhet-og-personvern'
      preLoaderRoute: typeof SikkerhetOgPersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slik-fungerer-det': {
      id: '/slik-fungerer-det'
      path: '/slik-fungerer-det'
      fullPath: '/slik-fungerer-det'
      preLoaderRoute: typeof SlikFungererDetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/banking-and-finance': {
      id: '/en/banking-and-finance'
      path: '/en/banking-and-finance'
      fullPath: '/en/banking-and-finance'
      preLoaderRoute: typeof EnBankingAndFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/enterprise-evaluation': {
      id: '/en/enterprise-evaluation'
      path: '/en/enterprise-evaluation'
      fullPath: '/en/enterprise-evaluation'
      preLoaderRoute: typeof EnEnterpriseEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/how-it-works': {
      id: '/en/how-it-works'
      path: '/en/how-it-works'
      fullPath: '/en/how-it-works'
      preLoaderRoute: typeof EnHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/hr-and-leadership': {
      id: '/en/hr-and-leadership'
      path: '/en/hr-and-leadership'
      fullPath: '/en/hr-and-leadership'
      preLoaderRoute: typeof EnHrAndLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/partners': {
      id: '/en/partners'
      path: '/en/partners'
      fullPath: '/en/partners'
      preLoaderRoute: typeof EnPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/pilot': {
      id: '/en/pilot'
      path: '/en/pilot'
      fullPath: '/en/pilot'
      preLoaderRoute: typeof EnPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/security-and-privacy': {
      id: '/en/security-and-privacy'
      path: '/en/security-and-privacy'
      fullPath: '/en/security-and-privacy'
      preLoaderRoute: typeof EnSecurityAndPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/use-cases': {
      id: '/en/use-cases'
      path: '/en/use-cases'
      fullPath: '/en/use-cases'
      preLoaderRoute: typeof EnUseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BruksomraderRoute: BruksomraderRoute,
  DchubRoute: DchubRoute,
  DemoRoute: DemoRoute,
  EnterpriseEvalueringRoute: EnterpriseEvalueringRoute,
  ForBankOgFinansRoute: ForBankOgFinansRoute,
  ForHrOgLedelseRoute: ForHrOgLedelseRoute,
  KontaktRoute: KontaktRoute,
  McpRoute: McpRoute,
  OmSelskapetRoute: OmSelskapetRoute,
  PartnereRoute: PartnereRoute,
  PilotRoute: PilotRoute,
  SikkerhetOgPersonvernRoute: SikkerhetOgPersonvernRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlikFungererDetRoute: SlikFungererDetRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EnAboutRoute: EnAboutRoute,
  EnBankingAndFinanceRoute: EnBankingAndFinanceRoute,
  EnContactRoute: EnContactRoute,
  EnEnterpriseEvaluationRoute: EnEnterpriseEvaluationRoute,
  EnHowItWorksRoute: EnHowItWorksRoute,
  EnHrAndLeadershipRoute: EnHrAndLeadershipRoute,
  EnPartnersRoute: EnPartnersRoute,
  EnPilotRoute: EnPilotRoute,
  EnSecurityAndPrivacyRoute: EnSecurityAndPrivacyRoute,
  EnUseCasesRoute: EnUseCasesRoute,
  EnIndexRoute: EnIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
